In [1]:
import numpy as np

In [2]:
temperaturas = np.random.uniform(15,40,30)
temperaturas

array([29.28016926, 17.71286947, 21.40548497, 36.46319213, 23.54598249,
       25.49555375, 37.45236332, 31.79382516, 39.21792634, 37.75405144,
       31.83822168, 37.3655756 , 33.29878198, 27.60293418, 35.75865742,
       15.27688651, 28.77470946, 16.61417037, 28.38984872, 25.03969316,
       27.02269719, 32.25421565, 33.5836973 , 27.82113785, 36.7547658 ,
       31.83885904, 23.39102288, 17.02938216, 39.72118457, 23.32827039])

In [3]:
matriz_temp = temperaturas.reshape(5,6)
matriz_temp

array([[29.28016926, 17.71286947, 21.40548497, 36.46319213, 23.54598249,
        25.49555375],
       [37.45236332, 31.79382516, 39.21792634, 37.75405144, 31.83822168,
        37.3655756 ],
       [33.29878198, 27.60293418, 35.75865742, 15.27688651, 28.77470946,
        16.61417037],
       [28.38984872, 25.03969316, 27.02269719, 32.25421565, 33.5836973 ,
        27.82113785],
       [36.7547658 , 31.83885904, 23.39102288, 17.02938216, 39.72118457,
        23.32827039]])

# Encuentra:
# - La temperatura máxima por semana
# - El día (índice) en que ocurrió la temperatura máxima por semana
# - La semana con mayor temperatura global

# - La temperatura máxima por semana

In [4]:
max_semana = np.max(matriz_temp,axis=1)
max_semana

array([36.46319213, 39.21792634, 35.75865742, 33.5836973 , 39.72118457])

# - El día (índice) en que ocurrió la temperatura máxima por semana

In [5]:
indice_max_semana = np.argmax(matriz_temp,axis=1)
indice_max_semana + 1

array([4, 3, 3, 5, 5])

# - La semana con mayor temperatura global

In [6]:
semana_max_global = np.argmax(max_semana)
semana_max_global + 1

np.int64(5)

# 2do ejercicio

In [22]:
# Paso 1: Genera una matriz de 10 alumnos x 3 exámenes (notas aleatorias entre 0 y 20)
notas = np.random.randint(0, 21, size=(10, 3))
notas

array([[10, 14, 16],
       [ 6,  9, 19],
       [20, 20,  6],
       [ 8, 15, 20],
       [20,  4, 20],
       [ 6, 11,  3],
       [ 9, 11, 13],
       [17,  6, 16],
       [16, 18,  5],
       [ 4, 17, 14]], dtype=int32)

# Encuentra:


*  El alumno con el mejor promedio
*  El examen donde el promedio general fue más bajo
* Ordena a los alumnos según su nota en el primer examen (índice 0)


*  El alumno con el mejor promedio

In [23]:
promedios = np.mean(notas, axis=1)
alumno_mejor = np.argmax(promedios)

alumno_mejor + 1

np.int64(3)

*  El examen donde el promedio general fue más bajo

In [24]:
examen_mas_bajo = np.argmin(promedios)

examen_mas_bajo + 1

np.int64(6)

* Ordena a los alumnos según su nota en el primer examen (índice 0)

In [25]:
orden = np.argsort(notas[:, 0])
notas_ordenadas = notas[orden]

orden + 1, notas_ordenadas

(array([10,  2,  6,  4,  7,  1,  9,  8,  5,  3]),
 array([[ 4, 17, 14],
        [ 6,  9, 19],
        [ 6, 11,  3],
        [ 8, 15, 20],
        [ 9, 11, 13],
        [10, 14, 16],
        [16, 18,  5],
        [17,  6, 16],
        [20,  4, 20],
        [20, 20,  6]], dtype=int32))